{
  "hash": "ed17990555e696978915b268f7bcc47a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Metodología\"\n---\n\nEn este capítulo, el objetivo reside en el cálculo de métricas sobre el contexto de los tiros basados en la posición de disparo y el contexto de la jugada a través del 360. A través de estas métricas, se define un sencillo modelo en el que se optimizan sus parámetros con el objetivo de ser lo más parecido posible a un modelo de xG. \n\nUna vez tenemos nuestro propio modelo de xG, podremos calcular, para cualquier posición del campo y contexto de jugadores, la probabilidad de meter gol. Con esta característica, seremos capaces de calcular, para cada tiro, si hacer un pase a otro compañero era mejor opción en términos de mejora de la probabilidad de gol en nuestro modelo. Se trabajará de forma análoga para los pases previos a un tiro. Se calculará la probabilidad de gol desde el punto donde llegó el pase, y se comparará con la probabilidad si se hubiera pasado a cualquier otro compañero.\n\n## Configuración del entorno y carga de datos.\n\nEl primer paso para establecer nuestro motor de cálculo es inicializar el entorno de trabajo. Para ello, importamos las librerías fundamentales para la manipulación estructurada de datos y la ejecución de operaciones vectoriales optimizadas. Asimismo, incluimos los módulos matemáticos estándar que nos permitirán aplicar cálculos trigonométricos sobre el plano bidimensional del terreno de juego.\n\nUna vez configurado el entorno, ingerimos los conjuntos de datos en formato optimizado (.parquet) que consolidamos durante la ingesta previa, garantizando que disponemos de la muestra exacta de acciones dinámicas en \"Open Play\" acompañadas de su contexto espacial (Freeze Frames).\n\n::: {#20b03c36 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport math\nfrom pathlib import Path\nimport ast\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.metrics import r2_score\n\nPATH_PROCESSED = Path(\"../data/processed\")\ndf_shots = pd.read_parquet(PATH_PROCESSED / \"shots_360_analysis.parquet\")\ndf_passes = pd.read_parquet(PATH_PROCESSED / \"shots_pass_360_analysis.parquet\")\n\ndef parse_spatial_data(val):\n    \"\"\"\n    Convierte representaciones en string de listas y diccionarios \n    a sus tipos nativos de Python de forma segura.\n    \"\"\"\n    if pd.isna(val):\n        return val\n    if isinstance(val, str):\n        try:\n            return ast.literal_eval(val)\n        except (ValueError, SyntaxError):\n            return val\n    return val\n\nespaciales_shots = [\n    'location', 'shot_end_location', \n    'visible_area', 'freeze_frame'\n]\n\nfor col in espaciales_shots:\n    if col in df_shots.columns:\n        df_shots[col] = df_shots[col].apply(parse_spatial_data)\n\n\nespaciales_secuencias = [\n    'location_pass', 'pass_end_location_pass', \n    'visible_area_360_pass', 'freeze_frame_360_pass',\n    'location_shot', 'shot_end_location_shot', \n    'visible_area_360_shot', 'freeze_frame_360_shot'\n]\n\nfor col in espaciales_secuencias:\n    if col in df_passes.columns:\n        df_passes[col] = df_passes[col].apply(parse_spatial_data)\n\n\n\ndel col, espaciales_secuencias, espaciales_shots, PATH_PROCESSED, parse_spatial_data\n```\n:::\n\n\n## Definición del campo y constantes geométricas.\n\nPara realizar el modelado matemático de las trayectorias de los disparos y los pases, es fundamental anclar nuestro sistema sobre las coordenadas estándar proporcionadas por la especificación oficial de StatsBomb.El terreno de juego se define en un plano bidimensional continuo cuyas dimensiones abarcan desde 0 hasta 120 metros en el eje X (longitud) y desde 0 hasta 80 metros en el eje Y (anchura). De acuerdo con la estructuración geométrica del dato espacial, los eventos siempre se orientan asumiendo que el equipo atacante progresa del valor mínimo al valor máximo del eje X. Por consiguiente, nuestro objetivo a batir siempre se situará sobre la línea de fondo $x = 120$. \n\n\nCon base en la ubicación de los postes, abstraeremos los elementos clave del campo utilizando la siguiente formalización matemática:  \n\n- Poste izquierdo: $P_{izq} = (120, 36)$\n- Poste derecho: $P_{der} = (120, 44)$\n- Centro de la portería: Obtenido mediante el punto medio de los postes, estableciendo $P_{cen} = (120, 40)$.- Volumen de oclusión ($r$): Para proyectar la oclusión espacial, modelaremos la silueta física de cada jugador dentro del Freeze Frame como un cuerpo circular con un radio $r = 0.5$ metros.\n\nA continuación, inicializamos estas coordenadas y métricas de contorno como variables constantes (en mayúsculas por convención) para su consumo posterior en los algoritmos de probabilidad.\n\n::: {#2f3bc8e8 .cell execution_count=2}\n``` {.python .cell-code}\nPITCH_LENGTH = 120.0\nPITCH_WIDTH = 80.0\nGOAL_POST_LEFT = (120.0, 36.0)\nGOAL_POST_RIGHT = (120.0, 44.0)\nGOAL_CENTER = (120.0, 40.0)\nPLAYER_RADIUS = 0.5 \n```\n:::\n\n\n## Creación de variables derivadas del 360.\n\nUna vez creadas las variables de referencia del terreno de juego, el siguiente paso de la metodología consiste en la creación de métricas tácticas explicativas sobre la posición de disparo. Aprovechando la posición desde la que se golpea y el contexto 360 de ese momento, vamos a extraer cuatro métricas para cada posible disparo desde una posición determinada del campo. \n\n### Distancia al centro de la portería\n\nLa distancia al objetivo es, históricamente, la variable de mayor peso en cualquier modelo de probabilidad de éxito. Utilizando el vector location del evento principal, calcularemos la distancia euclidiana exacta entre el origen del disparo (o pase) y nuestra constante central de la portería $P_{cen} = (120, 40)$. Para un punto de origen $(x, y)$, la distancia $d$ se define como:  \n$$d = \\sqrt{(120 - x)^2 + (40 - y)^2}$$\n\nImplementaremos este cálculo mediante una función modular en Python diseñada para recibir un array genérico de dos posiciones [x, y]. Este enfoque arquitectónico nos permite aplicar el cálculo geométrico tanto sobre la ubicación central del evento, como reutilizar la misma función de manera iterativa sobre las coordenadas individuales de cada jugador presente en los objetos anidados del freeze_frame. De este modo, garantizamos la consistencia matemática a lo largo de todo el análisis espacial.\n\n::: {#6b10aa29 .cell execution_count=3}\n``` {.python .cell-code}\ndef calcular_distancia_porteria(punto_origen, punto_destino=GOAL_CENTER):\n    \"\"\"\n    Calcula la distancia euclidiana desde una coordenada [x, y] \n    hasta un punto objetivo (por defecto, el centro de la portería).\n    \n    Parámetros:\n    - punto_origen: lista o tupla [x, y] con la ubicación a evaluar.\n    - punto_destino: tupla (X, Y) con las coordenadas del objetivo.\n    \n    Retorna:\n    - Distancia en metros (float) o NaN si el punto no es válido.\n    \"\"\"\n    # Verificamos que el input sea válido y tenga al menos X e Y\n    if not isinstance(punto_origen, (list, tuple)) or len(punto_origen) < 2:\n        return np.nan\n    \n    x, y = punto_origen[0], punto_origen[1]\n    gx, gy = punto_destino\n    \n    # Cálculo euclidiano puro\n    distancia = math.sqrt((gx - x)**2 + (gy - y)**2)\n    return distancia\n\n# Aplicamos la función sobre nuestra variable 'location' del DataFrame de tiros\ndf_shots['dist_centro_porteria'] = df_shots['location'].apply(calcular_distancia_porteria)\ndf_passes['dist_centro_porteria'] = df_passes['pass_end_location_pass'].apply(calcular_distancia_porteria)\n\n\nprint(df_shots[['player_name', 'location', 'dist_centro_porteria']].head(5).to_markdown(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       | location      |   dist_centro_porteria |\n|:------------------|:--------------|-----------------------:|\n| Granit Xhaka      | [92.2, 27.1]  |                30.6472 |\n| Timo Werner       | [107.0, 23.2] |                21.2424 |\n| Jonas Hofmann     | [96.2, 44.8]  |                24.2792 |\n| Ikoma Loïs Openda | [101.0, 28.8] |                22.0554 |\n| Benjamin Henrichs | [98.1, 29.8]  |                24.1588 |\n```\n:::\n:::\n\n\n### Ángulo del balón respecto a los palos\n\nEl ángulo de tiro, o shooting angle, define la amplitud de la \"ventana\" de gol que el rematador percibe en el momento del impacto. Matemáticamente, este se define como el ángulo formado por dos vectores que parten desde la ubicación del balón $(x, y)$ hacia los dos postes de la portería, situados en las coordenadas $P_{izq} = (120, 36)$ y $P_{der} = (120, 44)$.  \n\nUna mayor amplitud angular implica una mayor superficie de portería visible y, por tanto, una mayor probabilidad técnica de éxito. Para su cálculo, implementaremos una función que utilice el producto escalar de los vectores directores, obteniendo el ángulo $\\theta$ mediante la siguiente relación:\n$$\\cos(\\theta) = \\frac{\\vec{V_1} \\cdot \\vec{V_2}}{|\\vec{V_1}| \\cdot |\\vec{V_2}|}$$\n\nDonde $\\vec{V_1}$ y $\\vec{V_2}$ son los vectores desde el balón a los postes izquierdo y derecho, respectivamente.\n\n::: {#54c7002c .cell execution_count=4}\n``` {.python .cell-code}\ndef calcular_angulo_tiro(location):\n    \"\"\"\n    Calcula el ángulo de tiro disponible en grados.\n    \n    Parámetros:\n    - location: array [x, y] con la posición del jugador/balón.\n    \n    Retorna:\n    - Ángulo en grados (float).\n    \"\"\"\n    if not isinstance(location, (list, tuple, np.ndarray)) or len(location) < 2:\n        return np.nan\n        \n    x, y = location[0], location[1]\n    \n    # Definir vectores desde el balón a los palos\n    v1 = np.array([GOAL_POST_LEFT[0] - x, GOAL_POST_LEFT[1] - y])\n    v2 = np.array([GOAL_POST_RIGHT[0] - x, GOAL_POST_RIGHT[1] - y])\n    \n    # Calcular el producto escalar y las magnitudes\n    dot_product = np.dot(v1, v2)\n    norm_v1 = np.linalg.norm(v1)\n    norm_v2 = np.linalg.norm(v2)\n    \n    # Calcular coseno del ángulo y asegurar rango [-1, 1] para arccos\n    cos_theta = np.clip(dot_product / (norm_v1 * norm_v2), -1.0, 1.0)\n    \n    # Obtener ángulo en radianes y convertir a grados\n    angle_rad = np.arccos(cos_theta)\n    return np.degrees(angle_rad)\n\n# Aplicación sobre nuestro dataset\ndf_shots['angulo_tiro'] = df_shots['location'].apply(calcular_angulo_tiro)\ndf_passes['angulo_tiro'] = df_passes['pass_end_location_pass'].apply(calcular_angulo_tiro)\n\nprint(df_shots[['player_name', 'location', 'dist_centro_porteria', 'angulo_tiro']].head(4).to_markdown(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       | location      |   dist_centro_porteria |   angulo_tiro |\n|:------------------|:--------------|-----------------------:|--------------:|\n| Granit Xhaka      | [92.2, 27.1]  |                30.6472 |       13.5438 |\n| Timo Werner       | [107.0, 23.2] |                21.2424 |       13.4388 |\n| Jonas Hofmann     | [96.2, 44.8]  |                24.2792 |       18.3666 |\n| Ikoma Loïs Openda | [101.0, 28.8] |                22.0554 |       17.9057 |\n```\n:::\n:::\n\n\n### Número de jugadores dentro del cono de visión\n\nPara determinar si un jugador rival está bloqueando físicamente el ángulo de tiro, debemos modelar el \"cono\" como un triángulo cuyos vértices son: la posición del balón en posesión ($S$) y los dos postes de la portería, $P_{izq} = (120, 36)$ y $P_{der} = (120, 44)$.  \n\nUn punto $P$ (la posición de un rival) se encuentra dentro de este triángulo si cumple simultáneamente las condiciones de orientación respecto a los vectores que definen sus lados. La forma más robusta y eficiente de calcular esto en programación es mediante el producto vectorial en 2D. Para cada vector de lado del triángulo $\\vec{AB}$ y el punto $P$, el signo del producto vectorial $(B_x - A_x)(P_y - A_y) - (B_y - A_y)(P_x - A_x)$ nos indica si el punto está a la izquierda o a la derecha de la línea $AB$. Si al realizar esta operación para los tres lados del triángulo ($SP_{izq}$, $P_{izq}P_{der}$, y $P_{der}S$) los signos son consistentes (todos positivos o todos negativos), el punto $P$ está contenido dentro del área de visión.A continuación, implementamos la función que procesa el array de diccionarios freeze_frame (que contiene la información de los jugadores en ese instante) para filtrar y contar a los rivales que cumplan esta condición. \n\n::: {#b412aadb .cell execution_count=5}\n``` {.python .cell-code}\ndef calcular_jugadores_en_cono(shooter_location, freeze_frame):\n    \"\"\"\n    Calcula el número de compañeros, rivales y total de jugadores\n    dentro del cono de visión del lanzador.\n    \"\"\"\n    # Manejo de casos nulos o vacíos\n    if not isinstance(freeze_frame, list) or not isinstance(shooter_location, (list, np.ndarray)):\n        return 0, 0, 0\n    \n    # Definimos los vértices del triángulo (Postes y tirador)\n    S = np.array(shooter_location)\n    PL = np.array(GOAL_POST_LEFT)\n    PR = np.array(GOAL_POST_RIGHT)\n    \n    def es_punto_en_triangulo(p, s, pl, pr):\n        def cross_product(o, a, b):\n            return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])\n        \n        d1 = cross_product(s, pl, p)\n        d2 = cross_product(pl, pr, p)\n        d3 = cross_product(pr, s, p)\n        \n        has_neg = (d1 < 0) or (d2 < 0) or (d3 < 0)\n        has_pos = (d1 > 0) or (d2 > 0) or (d3 > 0)\n        \n        return not (has_neg and has_pos)\n\n    cont_teammates = 0\n    cont_opponents = 0\n    \n    for player in freeze_frame:\n        # Verificamos si el jugador está dentro del área\n        p = np.array(player['location'])\n        if es_punto_en_triangulo(p, S, PL, PR):\n            # Según la especificación 360, 'teammate' es booleano\n            if player.get('teammate', True):\n                cont_teammates += 1\n            else:\n                cont_opponents += 1\n                \n    total = cont_teammates + cont_opponents\n    return cont_teammates, cont_opponents, total\n\n# Aplicamos la función y expandimos en 3 nuevas columnas\n# result_type='expand' permite convertir la tupla de retorno en 3 columnas nuevas\ndf_shots[['compañeros_en_cono', 'rivales_en_cono', 'jugadores_en_cono']] = df_shots.apply(\n    lambda row: calcular_jugadores_en_cono(row['location'], row['freeze_frame']), \n    axis=1, \n    result_type='expand'\n)\n\ndf_passes[['compañeros_en_cono', 'rivales_en_cono', 'jugadores_en_cono']] = df_passes.apply(\n    lambda row: calcular_jugadores_en_cono(row['pass_end_location_pass'], row['freeze_frame_360_pass']), \n    axis=1, \n    result_type='expand'\n)\n\nprint(df_shots[['player_name', 'compañeros_en_cono', 'rivales_en_cono', 'jugadores_en_cono']].head(4).to_markdown(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       |   compañeros_en_cono |   rivales_en_cono |   jugadores_en_cono |\n|:------------------|---------------------:|------------------:|--------------------:|\n| Granit Xhaka      |                    0 |                 1 |                   1 |\n| Timo Werner       |                    0 |                 1 |                   1 |\n| Jonas Hofmann     |                    0 |                 3 |                   3 |\n| Ikoma Loïs Openda |                    0 |                 2 |                   2 |\n```\n:::\n:::\n\n\n### Distancia al rival más cercano dentro del ángulo de tiro\n\nUna vez que hemos filtrado los jugadores que ocupan el cono de visión del lanzador, calcularemos la intensidad de la presión defensiva. Para ello, buscamos el valor mínimo de las distancias euclidianas entre la posición del lanzador $S = (x_s, y_s)$ y la posición de cada jugador rival $R_i = (x_i, y_i)$ que se encuentre dentro del cono, según la siguiente expresión:\n$$d_{min} = \\min_{i \\in \\text{cono}} \\sqrt{(x_i - x_s)^2 + (y_i - y_s)^2}$$\n\nSi el conjunto de jugadores en el cono está vacío, asignaremos un valor suficientemente alto: 60.0\n\n::: {#d75f5505 .cell execution_count=6}\n``` {.python .cell-code}\ndef calcular_distancia_rival_cercano_cono(shooter_location, freeze_frame):\n    \"\"\"\n    Calcula la distancia al rival más cercano que se encuentre \n    dentro del cono de visión.\n    \"\"\"\n    if not isinstance(freeze_frame, list) or not isinstance(shooter_location, (list, np.ndarray)):\n        return 60.0\n        \n    def cross_product(o, a, b):\n        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])\n\n    shooter_loc = np.array(shooter_location)\n    distancias_en_cono = []\n    \n    for player in freeze_frame:\n        # Solo rivales (teammate = False)\n        if not player.get('teammate', True):\n            player_loc = np.array(player['location'])\n            \n            # Verificamos si está en el cono (reutilizamos lógica)\n            cp1 = cross_product(shooter_loc, GOAL_POST_LEFT, player_loc)\n            cp2 = cross_product(shooter_loc, player_loc, GOAL_POST_RIGHT)\n            \n            if cp1 > 0 and cp2 > 0:\n                # Calculamos distancia euclidiana\n                dist = np.linalg.norm(player_loc - shooter_loc)\n                distancias_en_cono.append(dist)\n                \n    if not distancias_en_cono:\n        return 60.0 # O 99.0 si prefieres un valor fijo para el modelo\n        \n    return min(distancias_en_cono)\n\n# Implementación sobre el dataframe\ndf_shots['dist_rival_cercano_cono'] = df_shots.apply(\n    lambda row: calcular_distancia_rival_cercano_cono(row['location'], row['freeze_frame']), axis=1\n)\n\ndf_passes['dist_rival_cercano_cono'] = df_passes.apply(\n    lambda row: calcular_distancia_rival_cercano_cono(row['pass_end_location_pass'], row['freeze_frame_360_pass']), \n    axis=1\n)\n\nprint(df_shots[['player_name', 'jugadores_en_cono', 'dist_rival_cercano_cono']].head(4).to_markdown())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n|    | player_name       |   jugadores_en_cono |   dist_rival_cercano_cono |\n|---:|:------------------|--------------------:|--------------------------:|\n|  0 | Granit Xhaka      |                   1 |                  11.353   |\n|  1 | Timo Werner       |                   1 |                  17.2666  |\n|  2 | Jonas Hofmann     |                   3 |                   6.59317 |\n|  3 | Ikoma Loïs Openda |                   2 |                   1.35084 |\n```\n:::\n:::\n\n\n## Fórmula: Cálculo de la probabilidad de meter gol.\n\nAntes de realizar la fórmula para estimar la probabilidad de meter gol según el contexto y distancia del lanzador a portería, vamos a revisar los rangos de valores de las 4 métricas numéricas recién calculadas. \n\n::: {#da9de76c .cell execution_count=7}\n``` {.python .cell-code}\n# Lista de las métricas que acabamos de generar\nmetricas = [\n    'dist_centro_porteria', \n    'angulo_tiro', \n    'jugadores_en_cono', \n    'dist_rival_cercano_cono'\n]\n\n# Calculamos un resumen estadístico básico\n# Usamos 'describe' para obtener min, max, media y percentiles\nresumen_stats = df_shots[metricas].describe().T[['min', 'max', 'mean', '50%']]\n\n# Añadimos un conteo de valores nulos, vital para saber si el 360 estaba vacío\nresumen_stats['null_count'] = df_shots[metricas].isnull().sum()\n\nprint(\"Resumen estadístico de las nuevas métricas:\")\nprint(resumen_stats.to_markdown())\n\ndel resumen_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nResumen estadístico de las nuevas métricas:\n|                         |      min |     max |    mean |      50% |   null_count |\n|:------------------------|---------:|--------:|--------:|---------:|-------------:|\n| dist_centro_porteria    | 3.32415  |  62.67  | 17.9219 | 17.3416  |            0 |\n| angulo_tiro             | 6.591    | 103.625 | 26.4734 | 21.2997  |            0 |\n| jugadores_en_cono       | 0        |   9     |  1.7669 |  1       |            0 |\n| dist_rival_cercano_cono | 0.384934 |  60     | 14.8851 |  9.02443 |            0 |\n```\n:::\n:::\n\n\nObservamos que hay valores de rival más cercano a 60, eso es debido a que, si no hay jugadores dentro del ángulo, ponemos esa distancia para evitar poner 0, lo que haría que el algoritmo detectara una presión muy fuerte sobre el jugador, algo irreal viendo las características de la situación\n\nUna vez asegurada la explicabilidad de cada métrica en los casos más extremos, creamos la fórmula base a utilizar: \n\n$$P(Gol) = \\exp\\left( - \\lambda \\cdot d_{porteria} - \\alpha \\cdot N_{cono} - \\frac{1 - \\alpha}{d_{rival}} \\right)$$\n\n- Distancia al centro de la portería ($d_{porteria}$): Al estar en el exponente con signo negativo, a mayor distancia desde la ubicación del disparo hasta el centro de la portería $(120, 40)$, la probabilidad cae exponencialmente. Es el factor de \"decaimiento\" principal. \n- Jugadores en el cono ($N_{cono}$): Representa la oclusión física. A mayor número de jugadores identificados en el freeze_frame dentro del triángulo de tiro, mayor es el valor sustraído del exponente, lo que reduce la probabilidad de gol al aumentar la probabilidad de bloqueo.  \n- Presión del rival más cercano ($d_{rival}$): Actúa como un factor de urgencia técnica. Al ser una función inversa ($\\frac{1}{d_{rival}}$), cuanto menor sea la distancia al defensor (es decir, mayor presión), más grande es el término sustraído, lo que penaliza la probabilidad debido a la reducción del tiempo y espacio para una ejecución limpia.\n\n::: {#4370cde3 .cell execution_count=8}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\n# Definición de los parámetros como constantes por defecto para facilitar el ajuste\nLAMBDA_DEFAULT = 0.08\nALPHA_DEFAULT = 0.6\n\ndef calcular_probabilidad_gol(num_rivales, dist_presion, dist_porteria, \n                              lambda_metrica=LAMBDA_DEFAULT, alpha=ALPHA_DEFAULT):\n    \"\"\"\n    Calcula la probabilidad de gol basada en la distancia, oclusión y presión.\n    \n    Parámetros ajustables:\n    - lambda_metrica: Peso de la distancia a portería.\n    - alpha: Peso de la densidad de defensores en el cono.\n    \"\"\"\n    # Manejo de casos nulos o inválidos\n    if pd.isna(dist_porteria) or dist_porteria <= 0:\n        return np.nan\n    \n    # Manejo de la presión: Si la distancia es nula o menor a 0.1 (evitar div por cero), \n    # tratamos la presión como máxima (penalización alta)\n    if pd.isna(dist_presion) or dist_presion < 0.1:\n        termino_presion = (1 - alpha) / 0.1 \n    else:\n        termino_presion = (1 - alpha) / dist_presion\n    \n    # Modelo exponencial: Probabilidad decae con el aumento de obstáculos\n    # P = exp(-(lambda * d_porteria) - (alpha * N) - (presion))\n    # Nota: El término de presión está normalizado respecto a ALPHA\n    prob = np.exp(\n        -(lambda_metrica * dist_porteria) \n        - (alpha * num_rivales) \n        - (termino_presion)\n    )\n    \n    return float(np.clip(prob, 0.0, 1.0))\n```\n:::\n\n\nUna vez hemos definido la fórmula a utilizar, ahora nuestro objetivo es definir la mejor combinación de parámetros que consigan mejor rendimiento respecto al modelo base de xG\n\n::: {#95456cb7 .cell execution_count=9}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom sklearn.model_selection import KFold\n\ndef optimize_xg_params(df, lambdas, alphas):\n    \"\"\"\n    Optimiza los parámetros del modelo xG basado en la correlación con \n    el xG de StatsBomb utilizando 5-Fold Cross-Validation.\n    \"\"\"\n    # 1. Definimos las variables de entrada necesarias\n    # (Asumimos que ya existen en tu df tras el preprocesamiento)\n    X = df[['dist_centro_porteria', 'jugadores_en_cono', 'dist_rival_cercano_cono', 'shot_statsbomb_xg']]\n    \n    kf = KFold(n_splits=5, shuffle=True, random_state=42)\n    best_corr = -1\n    best_params = (None, None)\n    \n    # 2. Bucle de búsqueda en el espacio de parámetros\n    for l in lambdas:\n        for a in alphas:\n            fold_corrs = []\n            \n            # 3. K-Fold Cross Validation\n            for train_idx, val_idx in kf.split(df):\n                val_data = df.iloc[val_idx].copy()\n                \n                # Calculamos nuestra probabilidad con los parámetros actuales\n                # Usando tu lógica de cálculo de presión y probabilidad\n                # (Asegúrate de que 'calcular_probabilidad_gol' esté definida en tu scope)\n                val_data['prob_model'] = val_data.apply(\n                    lambda row: calcular_probabilidad_gol(\n                        row['jugadores_en_cono'], \n                        row['dist_rival_cercano_cono'], \n                        row['dist_centro_porteria'], \n                        lambda_metrica=l, \n                        alpha=a\n                    ), axis=1\n                )\n                \n                # Correlación de Pearson en este fold\n                corr = val_data['prob_model'].corr(val_data['shot_statsbomb_xg'])\n                fold_corrs.append(corr)\n            \n            # Promediamos correlación de los 5 folds\n            avg_corr = np.mean([c for c in fold_corrs if not np.isnan(c)])\n            \n            # Guardamos el mejor\n            if avg_corr > best_corr:\n                best_corr = avg_corr\n                best_params = (l, a)\n                \n    return best_params, best_corr\n\n# --- Ejemplo de uso ---\n# Rangos de búsqueda recomendados para empezar\nlambdas_range = np.linspace(0.01, 0.5, 30)\nalphas_range = np.linspace(0.05, 0.95, 30)\n\nbest_p, best_c = optimize_xg_params(df_shots, lambdas_range, alphas_range)\n\nprint(f\"Mejor Lambda: {best_p[0]:.4f}\")\nprint(f\"Mejor Alpha: {best_p[1]:.4f}\")\nprint(f\"Correlación máxima con xG StatsBomb: {best_c:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMejor Lambda: 0.1790\nMejor Alpha: 0.1741\nCorrelación máxima con xG StatsBomb: 0.6591\n```\n:::\n:::\n\n\nEl término $-0.179 \\cdot d_{porteria}$ representa el decaimiento base. Por cada metro de distancia adicional que te alejas de la portería, el exponente sufre una penalización constante de 0.179. Es el esqueleto del modelo: un tiro desde 10 metros siempre tendrá, de base, un exponente de -1.79 antes de mirar qué hacen los defensas.\n\nEl término $-0.1741 \\cdot N_{cono}$ castiga cada jugador que se interpone en tu ángulo de visión hacia los palos. Como $\\lambda$ y $\\alpha$ son casi idénticos (0.179 frente a 0.1741), el modelo nos está diciendo que tener a un jugador más bloqueando la visión castiga tu probabilidad de gol casi lo mismo que alejar el tiro 1 metro más atrás.\n\nEl término $-\\frac{0.8259}{d_{rival}}$ es el más agresivo y el que define la urgencia de la toma de decisión. Al estar la distancia del rival dividiendo, su efecto se dispara cuando el defensor está muy cerca:Si el rival está a 5 metros (poca presión), la penalización es pequeña: $0.8259 / 5 = 0.165$.Si el rival te está encimando a 1 metro (presión extrema), la penalización explota a 0.8259.Para compensar esa presión de tener a un tío a un metro, tendrías que acercar el balón casi 4.6 metros hacia la portería ($0.8259 / 0.179$). Esto demuestra que el modelo pondera muchísimo el tiempo y espacio de ejecución: un tiro lejano pero totalmente libre de marca puede tener mejor xG que un tiro más cercano pero con un central echándose encima.\n\n::: {#0e533ed5 .cell execution_count=10}\n``` {.python .cell-code}\ndf_shots['formula_base'] = df_shots.apply(\n    lambda row: calcular_probabilidad_gol(row['jugadores_en_cono'], row['dist_rival_cercano_cono'], row['dist_centro_porteria'], lambda_metrica=0.179, alpha=0.1741), axis=1\n)\n\ndf_passes['formula_base'] = df_passes.apply(\n    lambda row: calcular_probabilidad_gol(row['jugadores_en_cono'], row['dist_rival_cercano_cono'], row['dist_centro_porteria'], lambda_metrica=0.179, alpha=0.1741), axis=1\n)\n\n\n# 1. Cálculo de métricas de ajuste\n# Correlación de Pearson\ncorrelacion = df_shots['formula_base'].corr(df_shots['shot_statsbomb_xg'])\n\n# Coeficiente de Determinación (R^2)\nr2 = r2_score(df_shots['shot_statsbomb_xg'], df_shots['formula_base'])\n\nprint(f\"--- RESULTADOS DE VALIDACIÓN ---\")\nprint(f\"Correlación de Pearson: {correlacion:.4f}\")\nprint(f\"Coeficiente de determinación (R^2): {r2:.4f}\")\n\n# 2. Visualización: Scatter plot para ver la dispersión\nplt.figure(figsize=(8, 6))\nsns.scatterplot(data=df_shots, x='formula_base', y='shot_statsbomb_xg', alpha=0.5)\n\n# Añadimos la línea de identidad (y=x)\nplt.plot([0, 1], [0, 1], color='red', linestyle='--', label='Línea de identidad (x=y)')\n\nplt.title('Comparación: Modelo Base vs StatsBomb xG')\nplt.xlabel('Probabilidad Base (Modelo Propio)')\nplt.ylabel('StatsBomb xG')\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--- RESULTADOS DE VALIDACIÓN ---\nCorrelación de Pearson: 0.6556\nCoeficiente de determinación (R^2): 0.2876\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](02_metodologia_files/figure-html/cell-11-output-2.png){width=663 height=524}\n:::\n:::\n\n\n## Cálculo del incremento en la probabilidad de gol respecto a compañeros libres.\n\nEn esta sección, el objetivo será calcular una métrica que nos explique la toma de decisión tanto de delanteros como de los asistentes (último pase). Para cada tiro/pase clave, evaluaremos dicho freeze-frame para identificar a todos los compañeros que pudieran recibir un pase desde esa posición. Si el pase no es interceptado en línea recta suponiendo que los defensores tienen un pequeño radio de 1 metro, entonces, calculamos la probabilidad de meter gol desde la posición del compañero. Haremos esto para cada compañero visible y nos quedaremos con la probabilidad máxima del mejor compañero visible. Con esta probabilidad, seremos capaces de, para cada pase/tiro, calcular el incremento en la probabilidad si se hubiera tomado otra decisión. \n\n::: {#270f67a8 .cell execution_count=11}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\n# Valor centinela para cuando no hay rivales (libertad total)\nVALOR_LIBERTAD_TOTAL = 60.0\n\ndef esta_en_fuera_de_juego(pos, balon_x, linea_defensiva_x):\n    \"\"\"Verifica si un jugador está en fuera de juego.\"\"\"\n    return pos[0] > linea_defensiva_x and pos[0] > balon_x\n\ndef esta_linea_bloqueada(origen, destino, rivales, radio_bloqueo=0.5):\n    \"\"\"Verifica si la trayectoria está bloqueada por algún rival[cite: 2, 3].\"\"\"\n    p1, p2 = np.array(origen), np.array(destino)\n    for rival in rivales:\n        r = np.array(rival['location'])\n        # Consideramos el radio del jugador (0.5m)\n        if np.linalg.norm(r - p1) < 0.5: continue \n        dist = np.abs(np.cross(p2-p1, p1-r)) / np.linalg.norm(p2-p1)\n        if dist < radio_bloqueo: return True\n    return False\n\ndef calcular_mejor_opcion_tiro_con_bloqueo(row, freeze_frame_col, radio_bloqueo=1, radio_percepcion=15.0):\n    \"\"\"\n    Calcula la probabilidad de gol de los compañeros en un radio restrictivo de 30 yardas.\n    Sin factores de corrección de pase, solo la probabilidad de la fórmula pura.\n    \"\"\"\n    frame = row[freeze_frame_col]\n    if not isinstance(frame, list):\n        return np.nan\n    \n    actor_loc = next((p['location'] for p in frame if p.get('actor', False)), None)\n    if actor_loc is None: return np.nan\n    \n    # Identificar línea defensiva para fuera de juego\n    rivales_x = sorted([p['location'][0] for p in frame if not p.get('teammate', True)], reverse=True)\n    penultimo_defensor_x = rivales_x[1] if len(rivales_x) > 1 else 120.0\n    \n    rivales_en_frame = [p for p in frame if not p.get('teammate', True) and not p.get('actor', False)]\n    probabilidades = []\n    \n    for player in frame:\n        if player.get('teammate', True) and not player.get('actor', False):\n            pos = player['location']\n            \n            # FILTRO ESPACIAL MÁS RESTRICTIVO: 30 yardas\n            dist_al_actor = np.linalg.norm(np.array(pos) - np.array(actor_loc))\n            if dist_al_actor > radio_percepcion:\n                continue\n            \n            # FILTRO: Fuera de juego\n            if esta_en_fuera_de_juego(pos, actor_loc[0], penultimo_defensor_x):\n                continue\n            \n            # FILTRO: Bloqueo línea de tiro[cite: 3]\n            if esta_linea_bloqueada(pos, GOAL_CENTER, rivales_en_frame, radio_bloqueo):\n                continue\n            \n            # CÁLCULO DE PROBABILIDAD PURA\n            dist_p = calcular_distancia_porteria(pos)\n            _, rivales, _ = calcular_jugadores_en_cono(pos, frame)\n            \n            # Aplicamos centinela para presión nula\n            dist_rival = calcular_distancia_rival_cercano_cono(pos, frame)\n            dist_presion = dist_rival if not pd.isna(dist_rival) else VALOR_LIBERTAD_TOTAL\n            \n            # Probabilidad tal cual\n            p_gol = calcular_probabilidad_gol(rivales, dist_presion, dist_p)\n            probabilidades.append(p_gol)\n            \n    return max(probabilidades) if probabilidades else 0.0\n\n# --- Aplicación ---\ndf_shots['mejor_prob_posible'] = df_shots.apply(\n    lambda row: calcular_mejor_opcion_tiro_con_bloqueo(row, 'freeze_frame'), axis=1\n)\n\ndf_passes['prob_opcion_pase_tiro'] = df_passes.apply(\n    lambda row: calcular_mejor_opcion_tiro_con_bloqueo(row, 'freeze_frame_360_pass'), axis=1\n)\n```\n:::\n\n\nAhora, calculamos cuántos pases y tiros mejorarían si se tomara otra decisión: \n\n::: {#87e521f7 .cell execution_count=12}\n``` {.python .cell-code}\n# Calcular porcentajes de mejora\npct_shots_mejor = (df_shots['mejor_prob_posible'] > df_shots['formula_base']).mean() * 100\npct_passes_mejor = (df_passes['prob_opcion_pase_tiro'] > df_passes['shot_statsbomb_xg_shot']).mean() * 100\n\n# Print resumen\nprint(f\"--- RESUMEN DE MEJORA EN DECISIONES ---\")\nprint(f\"% de tiros donde pasar habría dado más probabilidad: {pct_shots_mejor:.2f}%\")\nprint(f\"% de pases donde otra opción habría sido mejor: {pct_passes_mejor:.2f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n--- RESUMEN DE MEJORA EN DECISIONES ---\n% de tiros donde pasar habría dado más probabilidad: 48.72%\n% de pases donde otra opción habría sido mejor: 24.17%\n```\n:::\n:::\n\n\nPor último, nos cargamos ambos dataframes de nuevo para la parte de resultados: \n\n::: {#89132b3c .cell execution_count=13}\n``` {.python .cell-code}\ndf_passes.to_parquet(\"../data/processed/pases_post_metodologia.parquet\", index=False)\ndf_shots.to_parquet(\"../data/processed/tiros_post_metodologia.parquet\", index = False)\n```\n:::\n\n\n",
    "supporting": [
      "02_metodologia_files"
    ],
    "filters": [],
    "includes": {}
  }
}