{
  "hash": "ed17990555e696978915b268f7bcc47a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Metodología\"\n---\n\nEn este capítulo, el objetivo reside en el cálculo de métricas sobre el contexto de los tiros basados en la posición de disparo y el contexto de la jugada a través del 360. A través de estas métricas, se define un sencillo modelo en el que se optimizan sus parámetros con el objetivo de ser lo más parecido posible a un modelo de xG. \n\nUna vez tenemos nuestro propio modelo de xG, podremos calcular, para cualquier posición del campo y contexto de jugadores, la probabilidad de meter gol. Con esta característica, seremos capaces de calcular, para cada tiro, si hacer un pase a otro compañero era mejor opción en términos de mejora de la probabilidad de gol en nuestro modelo. Se trabajará de forma análoga para los pases previos a un tiro. Se calculará la probabilidad de gol desde el punto donde llegó el pase, y se comparará con la probabilidad si se hubiera pasado a cualquier otro compañero.\n\n## Configuración del entorno y carga de datos.\n\nEl primer paso para establecer nuestro motor de cálculo es inicializar el entorno de trabajo. Para ello, importamos las librerías fundamentales para la manipulación estructurada de datos y la ejecución de operaciones vectoriales optimizadas. Asimismo, incluimos los módulos matemáticos estándar que nos permitirán aplicar cálculos trigonométricos sobre el plano bidimensional del terreno de juego.\n\nUna vez configurado el entorno, ingerimos los conjuntos de datos en formato optimizado (.parquet) que consolidamos durante la ingesta previa, garantizando que disponemos de la muestra exacta de acciones dinámicas en \"Open Play\" acompañadas de su contexto espacial (Freeze Frames).\n\n\n\n## Definición del campo y constantes geométricas.\n\nPara realizar el modelado matemático de las trayectorias de los disparos y los pases, es fundamental anclar nuestro sistema sobre las coordenadas estándar proporcionadas por la especificación oficial de StatsBomb.El terreno de juego se define en un plano bidimensional continuo cuyas dimensiones abarcan desde 0 hasta 120 metros en el eje X (longitud) y desde 0 hasta 80 metros en el eje Y (anchura). De acuerdo con la estructuración geométrica del dato espacial, los eventos siempre se orientan asumiendo que el equipo atacante progresa del valor mínimo al valor máximo del eje X. Por consiguiente, nuestro objetivo a batir siempre se situará sobre la línea de fondo $x = 120$. \n\n\nCon base en la ubicación de los postes, abstraeremos los elementos clave del campo utilizando la siguiente formalización matemática:  \n\n- Poste izquierdo: $P_{izq} = (120, 36)$\n- Poste derecho: $P_{der} = (120, 44)$\n- Centro de la portería: Obtenido mediante el punto medio de los postes, estableciendo $P_{cen} = (120, 40)$.- Volumen de oclusión ($r$): Para proyectar la oclusión espacial, modelaremos la silueta física de cada jugador dentro del Freeze Frame como un cuerpo circular con un radio $r = 0.5$ metros.\n\nA continuación, inicializamos estas coordenadas y métricas de contorno como variables constantes (en mayúsculas por convención) para su consumo posterior en los algoritmos de probabilidad.\n\n\n\n## Creación de variables derivadas del 360.\n\nUna vez creadas las variables de referencia del terreno de juego, el siguiente paso de la metodología consiste en la creación de métricas tácticas explicativas sobre la posición de disparo. Aprovechando la posición desde la que se golpea y el contexto 360 de ese momento, vamos a extraer cuatro métricas para cada posible disparo desde una posición determinada del campo. \n\n### Distancia al centro de la portería\n\nLa distancia al objetivo es, históricamente, la variable de mayor peso en cualquier modelo de probabilidad de éxito. Utilizando el vector location del evento principal, calcularemos la distancia euclidiana exacta entre el origen del disparo (o pase) y nuestra constante central de la portería $P_{cen} = (120, 40)$. Para un punto de origen $(x, y)$, la distancia $d$ se define como:  \n$$d = \\sqrt{(120 - x)^2 + (40 - y)^2}$$\n\nImplementaremos este cálculo mediante una función modular en Python diseñada para recibir un array genérico de dos posiciones [x, y]. Este enfoque arquitectónico nos permite aplicar el cálculo geométrico tanto sobre la ubicación central del evento, como reutilizar la misma función de manera iterativa sobre las coordenadas individuales de cada jugador presente en los objetos anidados del freeze_frame. De este modo, garantizamos la consistencia matemática a lo largo de todo el análisis espacial.\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       | location      |   dist_centro_porteria |\n|:------------------|:--------------|-----------------------:|\n| Granit Xhaka      | [92.2, 27.1]  |                30.6472 |\n| Timo Werner       | [107.0, 23.2] |                21.2424 |\n| Jonas Hofmann     | [96.2, 44.8]  |                24.2792 |\n| Ikoma Loïs Openda | [101.0, 28.8] |                22.0554 |\n| Benjamin Henrichs | [98.1, 29.8]  |                24.1588 |\n```\n:::\n:::\n\n\n### Ángulo del balón respecto a los palos\n\nEl ángulo de tiro, o shooting angle, define la amplitud de la \"ventana\" de gol que el rematador percibe en el momento del impacto. Matemáticamente, este se define como el ángulo formado por dos vectores que parten desde la ubicación del balón $(x, y)$ hacia los dos postes de la portería, situados en las coordenadas $P_{izq} = (120, 36)$ y $P_{der} = (120, 44)$.  \n\nUna mayor amplitud angular implica una mayor superficie de portería visible y, por tanto, una mayor probabilidad técnica de éxito. Para su cálculo, implementaremos una función que utilice el producto escalar de los vectores directores, obteniendo el ángulo $\\theta$ mediante la siguiente relación:\n$$\\cos(\\theta) = \\frac{\\vec{V_1} \\cdot \\vec{V_2}}{|\\vec{V_1}| \\cdot |\\vec{V_2}|}$$\n\nDonde $\\vec{V_1}$ y $\\vec{V_2}$ son los vectores desde el balón a los postes izquierdo y derecho, respectivamente.\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       | location      |   dist_centro_porteria |   angulo_tiro |\n|:------------------|:--------------|-----------------------:|--------------:|\n| Granit Xhaka      | [92.2, 27.1]  |                30.6472 |       13.5438 |\n| Timo Werner       | [107.0, 23.2] |                21.2424 |       13.4388 |\n| Jonas Hofmann     | [96.2, 44.8]  |                24.2792 |       18.3666 |\n| Ikoma Loïs Openda | [101.0, 28.8] |                22.0554 |       17.9057 |\n```\n:::\n:::\n\n\n### Número de jugadores dentro del cono de visión\n\nPara determinar si un jugador rival está bloqueando físicamente el ángulo de tiro, debemos modelar el \"cono\" como un triángulo cuyos vértices son: la posición del balón en posesión ($S$) y los dos postes de la portería, $P_{izq} = (120, 36)$ y $P_{der} = (120, 44)$.  \n\nUn punto $P$ (la posición de un rival) se encuentra dentro de este triángulo si cumple simultáneamente las condiciones de orientación respecto a los vectores que definen sus lados. La forma más robusta y eficiente de calcular esto en programación es mediante el producto vectorial en 2D. Para cada vector de lado del triángulo $\\vec{AB}$ y el punto $P$, el signo del producto vectorial $(B_x - A_x)(P_y - A_y) - (B_y - A_y)(P_x - A_x)$ nos indica si el punto está a la izquierda o a la derecha de la línea $AB$. Si al realizar esta operación para los tres lados del triángulo ($SP_{izq}$, $P_{izq}P_{der}$, y $P_{der}S$) los signos son consistentes (todos positivos o todos negativos), el punto $P$ está contenido dentro del área de visión.A continuación, implementamos la función que procesa el array de diccionarios freeze_frame (que contiene la información de los jugadores en ese instante) para filtrar y contar a los rivales que cumplan esta condición. \n\n::: {.cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n| player_name       |   compañeros_en_cono |   rivales_en_cono |   jugadores_en_cono |\n|:------------------|---------------------:|------------------:|--------------------:|\n| Granit Xhaka      |                    0 |                 1 |                   1 |\n| Timo Werner       |                    0 |                 1 |                   1 |\n| Jonas Hofmann     |                    0 |                 3 |                   3 |\n| Ikoma Loïs Openda |                    0 |                 2 |                   2 |\n```\n:::\n:::\n\n\n### Distancia al rival más cercano dentro del ángulo de tiro\n\nUna vez que hemos filtrado los jugadores que ocupan el cono de visión del lanzador, calcularemos la intensidad de la presión defensiva. Para ello, buscamos el valor mínimo de las distancias euclidianas entre la posición del lanzador $S = (x_s, y_s)$ y la posición de cada jugador rival $R_i = (x_i, y_i)$ que se encuentre dentro del cono, según la siguiente expresión:\n$$d_{min} = \\min_{i \\in \\text{cono}} \\sqrt{(x_i - x_s)^2 + (y_i - y_s)^2}$$\n\nSi el conjunto de jugadores en el cono está vacío, asignaremos un valor suficientemente alto: 60.0\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\n|    | player_name       |   jugadores_en_cono |   dist_rival_cercano_cono |\n|---:|:------------------|--------------------:|--------------------------:|\n|  0 | Granit Xhaka      |                   1 |                  11.353   |\n|  1 | Timo Werner       |                   1 |                  17.2666  |\n|  2 | Jonas Hofmann     |                   3 |                   6.59317 |\n|  3 | Ikoma Loïs Openda |                   2 |                   1.35084 |\n```\n:::\n:::\n\n\n## Fórmula: Cálculo de la probabilidad de meter gol.\n\nAntes de realizar la fórmula para estimar la probabilidad de meter gol según el contexto y distancia del lanzador a portería, vamos a revisar los rangos de valores de las 4 métricas numéricas recién calculadas. \n\n::: {.cell execution_count=7}\n\n::: {.cell-output .cell-output-stdout}\n```\nResumen estadístico de las nuevas métricas:\n|                         |      min |     max |    mean |      50% |   null_count |\n|:------------------------|---------:|--------:|--------:|---------:|-------------:|\n| dist_centro_porteria    | 3.32415  |  62.67  | 17.9219 | 17.3416  |            0 |\n| angulo_tiro             | 6.591    | 103.625 | 26.4734 | 21.2997  |            0 |\n| jugadores_en_cono       | 0        |   9     |  1.7669 |  1       |            0 |\n| dist_rival_cercano_cono | 0.384934 |  60     | 14.8851 |  9.02443 |            0 |\n```\n:::\n:::\n\n\nObservamos que hay valores de rival más cercano a 60, eso es debido a que, si no hay jugadores dentro del ángulo, ponemos esa distancia para evitar poner 0, lo que haría que el algoritmo detectara una presión muy fuerte sobre el jugador, algo irreal viendo las características de la situación\n\nUna vez asegurada la explicabilidad de cada métrica en los casos más extremos, creamos la fórmula base a utilizar: \n\n$$P(Gol) = \\exp\\left( - \\lambda \\cdot d_{porteria} - \\alpha \\cdot N_{cono} - \\frac{1 - \\alpha}{d_{rival}} \\right)$$\n\n- Distancia al centro de la portería ($d_{porteria}$): Al estar en el exponente con signo negativo, a mayor distancia desde la ubicación del disparo hasta el centro de la portería $(120, 40)$, la probabilidad cae exponencialmente. Es el factor de \"decaimiento\" principal. \n- Jugadores en el cono ($N_{cono}$): Representa la oclusión física. A mayor número de jugadores identificados en el freeze_frame dentro del triángulo de tiro, mayor es el valor sustraído del exponente, lo que reduce la probabilidad de gol al aumentar la probabilidad de bloqueo.  \n- Presión del rival más cercano ($d_{rival}$): Actúa como un factor de urgencia técnica. Al ser una función inversa ($\\frac{1}{d_{rival}}$), cuanto menor sea la distancia al defensor (es decir, mayor presión), más grande es el término sustraído, lo que penaliza la probabilidad debido a la reducción del tiempo y espacio para una ejecución limpia.\n\n\n\nUna vez hemos definido la fórmula a utilizar, ahora nuestro objetivo es definir la mejor combinación de parámetros que consigan mejor rendimiento respecto al modelo base de xG\n\n::: {.cell execution_count=9}\n\n::: {.cell-output .cell-output-stdout}\n```\nMejor Lambda: 0.1790\nMejor Alpha: 0.1741\nCorrelación máxima con xG StatsBomb: 0.6591\n```\n:::\n:::\n\n\nEl término $-0.179 \\cdot d_{porteria}$ representa el decaimiento base. Por cada metro de distancia adicional que te alejas de la portería, el exponente sufre una penalización constante de 0.179. Es el esqueleto del modelo: un tiro desde 10 metros siempre tendrá, de base, un exponente de -1.79 antes de mirar qué hacen los defensas.\n\nEl término $-0.1741 \\cdot N_{cono}$ castiga cada jugador que se interpone en tu ángulo de visión hacia los palos. Como $\\lambda$ y $\\alpha$ son casi idénticos (0.179 frente a 0.1741), el modelo nos está diciendo que tener a un jugador más bloqueando la visión castiga tu probabilidad de gol casi lo mismo que alejar el tiro 1 metro más atrás.\n\nEl término $-\\frac{0.8259}{d_{rival}}$ es el más agresivo y el que define la urgencia de la toma de decisión. Al estar la distancia del rival dividiendo, su efecto se dispara cuando el defensor está muy cerca:Si el rival está a 5 metros (poca presión), la penalización es pequeña: $0.8259 / 5 = 0.165$.Si el rival te está encimando a 1 metro (presión extrema), la penalización explota a 0.8259.Para compensar esa presión de tener a un tío a un metro, tendrías que acercar el balón casi 4.6 metros hacia la portería ($0.8259 / 0.179$). Esto demuestra que el modelo pondera muchísimo el tiempo y espacio de ejecución: un tiro lejano pero totalmente libre de marca puede tener mejor xG que un tiro más cercano pero con un central echándose encima.\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-stdout}\n```\n--- RESULTADOS DE VALIDACIÓN ---\nCorrelación de Pearson: 0.6556\nCoeficiente de determinación (R^2): 0.2876\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](02_metodologia_files/figure-pdf/cell-11-output-2.pdf){}\n:::\n:::\n\n\n## Cálculo del incremento en la probabilidad de gol respecto a compañeros libres.\n\nEn esta sección, el objetivo será calcular una métrica que nos explique la toma de decisión tanto de delanteros como de los asistentes (último pase). Para cada tiro/pase clave, evaluaremos dicho freeze-frame para identificar a todos los compañeros que pudieran recibir un pase desde esa posición. Si el pase no es interceptado en línea recta suponiendo que los defensores tienen un pequeño radio de 1 metro, entonces, calculamos la probabilidad de meter gol desde la posición del compañero. Haremos esto para cada compañero visible y nos quedaremos con la probabilidad máxima del mejor compañero visible. Con esta probabilidad, seremos capaces de, para cada pase/tiro, calcular el incremento en la probabilidad si se hubiera tomado otra decisión. \n\n\n\nAhora, calculamos cuántos pases y tiros mejorarían si se tomara otra decisión: \n\n::: {.cell execution_count=12}\n\n::: {.cell-output .cell-output-stdout}\n```\n--- RESUMEN DE MEJORA EN DECISIONES ---\n% de tiros donde pasar habría dado más probabilidad: 48.72%\n% de pases donde otra opción habría sido mejor: 24.17%\n```\n:::\n:::\n\n\nPor último, nos cargamos ambos dataframes de nuevo para la parte de resultados: \n\n\n\n",
    "supporting": [
      "02_metodologia_files\\figure-pdf"
    ],
    "filters": []
  }
}