{
  "hash": "42b83e6fcb59b0998b649131beb6da66",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Preprocesamiento de los datos\"\n---\n\nEn este capítulo, el objetivo será construir el conjunto de datos inicial sobre el que vamos a calcular las métricas necesarias para hacer el estudio sobre las finalizaciones y sus tiros previos. \n\n## Ingesta y Extracción de Datos Base\n\nEn esta fase inicial, establecemos los cimientos de nuestro conjunto de datos analítico procesando la materia prima suministrada por StatsBomb. Dado el considerable volumen computacional que implica cargar el historial completo de eventos de una competición, implementamos una estrategia de filtrado en origen.\n\nEl proceso recorre secuencialmente el directorio de eventos procesados. Por cada partido, dividimos la información en dos flujos principales:\n\n1. Disparos (Shots): Todos los tiros registrados por StatsBomb.\n2. Pases Clave (Key Passes): Aquellos pases que están referenciados directamente como la acción previa a un disparo, garantizando la trazabilidad de la secuencia ofensiva. \n\nSimultáneamente, extraemos y consolidamos los datos de cada partido cargando el diccionario de partidos y las alineaciones de cada uno. De esta manera podremos enriquecer posteriormente los análisis realizados. \n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-stdout}\n```\nIniciando la ingesta de datos a nivel global...\n\n--- REPORTE DE INGESTA DE DATOS (MUESTRA TOTAL) ---\nTotal de disparos extraídos (Todos los equipos): 916\nTotal de pases clave asociados extraídos: 690\nTotal de partidos procesados: 34\nTotal de registros de alineación procesados: 68\n```\n:::\n:::\n\n\nLa diferencia entre la muestra total de disparos y los pases clave asociados es un patrón absolutamente normal. Esta reducción en los pases clave ocurre generalmente porque el evento general de disparo engloba finalizaciones que carecen de un pasador previo, tales como las acciones directas a balón parado (como penalties o tiros libre) o jugadas individuales donde el rematador finaliza tras crear su propia ventaja posicional. \n\nLos modelos que construiremos en este trabajo se basan en la toma de decisiones tanto del lanzador como en la del pasador. Por lo tanto, el siguiente paso consiste en filtrar los disparos para quedarnos con aquellos producidos en situación de \"Open Play\". Excluiremos jugadas precedidas de córner, penalties o tiros libres.\n\n\n## Filtrado de Contexto Dinámico (Open Play) y unificación de secuencias\n\nUna vez consolidada la extracción de eventos, el siguiente paso de nuestro pipeline consiste en seleccionar la muestra para alinearla con los objetivos de la investigación a realizar. Dado que buscamos evaluar la toma de decisiones tácticas y la oclusión en escenarios de juego fluido, debemos descartar aquellas finalizaciones originadas a balón parado. \n\nPara ello, aplicamos un filtro sobre la tipología específica del disparo (shot.type), conservando de manera exclusiva los remates categorizados como \"Open Play\". Esta operación elimina de nuestra muestra poblacional los lanzamientos de penalti, los tiros libres directos y los saques de esquina directos, dejándonos tanto los tiros asistidos en dinámica como las jugadas individuales autónomas.\n\nPosteriormente, construimos nuestro dataset relacional de secuencias ofensivas. Mediante una operación de unión (join), enlazamos estructuralmente los pases clave con sus correspondientes disparos en \"Open Play\". Utilizando el identificador único del pase y la variable de enlace del disparo (shot_key_pass_id), logramos colapsar la secuencia temporal \"Pase -> Tiro\" en una única fila plana.\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n\n--- REPORTE DE SECUENCIAS OPEN PLAY ---\nTotal de disparos globales iniciales: 916\nTotal de pases clave iniciales: 690\nDisparos aislados en 'Open Play': 882\nSecuencias completas ensambladas (Pase -> Tiro en Open Play): 690\n```\n:::\n:::\n\n\nLos resultados nos proporcionan un mapa claro del volumen de datos útiles para nuestro estudio. Tras aplicar el filtro de juego dinámico, disponemos de una población exacta de 882 disparos en \"Open Play\". Este será el conjunto de datos principal sobre el que evaluaremos la toma de decisiones, la ejecución y el posicionamiento de los rematadores, independientemente de si generaron su propia ventaja o si recibieron el balón de un compañero.\n\nPor otro lado, la operación de unión relacional nos confirma un total de 690 secuencias completas (Pase clave -> Tiro). Esta submuestra representa nuestro núcleo analítico de mayor valor para estudiar la perspectiva de los asistidores, permitiéndonos evaluar el contexto previo a la finalización y analizar cómo sus pases habilitaron el espacio para el tirador.\n\nCon los eventos de tiro filtrados y las secuencias tiro/pase construidas, el siguiente paso metodológico consistirá en dotar a estas acciones de su correspondiente contexto 360.\n\n## Integración del Contexto Espacial (StatsBomb 360)\n\nLa precisión de los modelos a construir posteriormente depende intrínsecamente de la disponibilidad de las coordenadas de los jugadores en los momentos críticos de la jugada. En esta fase, integramos la capa espacial StatsBomb 360, la cual captura las ubicaciones del ecosistema de jugadores en el instante exacto de la acción.\n\nPara aislar nuestra muestra definitiva de estudio, implementamos dos operaciones de unión relacional restrictiva (inner joins) utilizando el identificador único del evento (event_uuid):\n\n1. **Disparos aislados**: Cruzamos la población de remates *Open Play* con la base de datos 360, descartando disparos que no tengan asignado freeze frame. \n\n2. **Secuencias Pase/tiro**: Aplicamos dos uniones. Exigimos que, para analizar posteriormente estas secuencias, necesitamos el 360 del pase clave y del tiro. Si uno de los dos eventos carece del 360, la secuencia se elimina del análisis. \n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\n\n--- REPORTE DE INTEGRACIÓN ESPACIAL 360 ---\nTiros 'Open Play' originales: 882\nTiros 'Open Play' con contexto 360: 858\n----------------------------------------\nSecuencias Pase->Tiro originales: 690\nSecuencias perfectas (360 en Pase Y Tiro): 600\n```\n:::\n:::\n\n\nPara la rama del estudio centrada en el comportamiento de los finalizadores, la muestra definitiva consolida 858 disparos dinámicos con cobertura espacial absoluta. Esto representa una retención excepcional del 93.6% sobre el volumen ofensivo global inicial de la competición (916 tiros totales), alcanzando un asombroso 97.3% de eficacia si acotamos la métrica exclusivamente a los 882 remates originados en estricto Open Play.\n\nPor otro lado, para el segundo enfoque de la investigación sobre la toma de decisiones de los pasadores, tenemos un total de 600 secuencias de pase y tiro con el 360 integrado. Esto significa que logramos retener el 87% de los 690 pases clave originales.\n\nCon los dataset finales ya creados, el siguiente objetivo será elegir las variables necesarias para comenzar el análisis en profundidad para la creación de nuevas métricas.\n\n## Selección de Variables\n\nEn esta etapa final del pre-procesamiento, vamos a elegir las variables sólamente necesarias de cada dataframe para reducir la dimensionalidad. Sólamente conservaremos las variables necesarias tanto para la creación de nuevas métricas como para la posterior validación. \n\n\n\n## Exportación de los Datasets\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\n# Guardado final optimizado\ndf_matches_final.to_parquet(\"../data/processed/matches_metadata.parquet\", index=False)\ndf_lineups_final.to_parquet(\"../data/processed/lineups_metadata.parquet\", index=False)\ndf_shots_360_final.to_parquet(\"../data/processed/shots_360_analysis.parquet\", index=False)\ndf_secuencias_final.to_parquet(\"../data/processed/shots_pass_360_analysis.parquet\", index=False)\n```\n:::\n\n\n",
    "supporting": [
      "01_data_preprocessing_files\\figure-pdf"
    ],
    "filters": []
  }
}